import { Medication, VitalMetric, DayVitals, ClinicalDocument, CaregiverAlert, PatientProfile } from './types';

export const initialPatient: PatientProfile = {
  name: 'Arthur Vance',
  age: 74,
  gender: 'Male',
  bloodType: 'O Positive',
  idNumber: 'MED-7492-US',
  emergencyContact: {
    name: 'Sarah Kendrick',
    relationship: 'Daughter (Primary Caregiver)',
    phone: '+1 (312) 555-0192',
  },
  primaryDoctor: {
    name: 'Dr. Aris Thorne, MD',
    specialty: 'Cardiovascular & Internal Medicine',
    clinic: 'Metropolitan Medical Center',
    phone: '+1 (312) 555-4820',
  },
  allergies: ['Penicillin (Moderate rash)', 'Sulfa Drugs'],
  conditions: ['Hypertension (Stage 1)', 'Type 2 Diabetes (Managed)', 'Hyperlipidemia'],
  adherenceRate: 98,
  streakDays: 14,
};

export const initialMedications: Medication[] = [
  {
    id: 'med-1',
    name: 'Atorvastatin',
    dosage: '20mg',
    instructions: '1 Tablet • With Breakfast',
    scheduledTime: '08:00 AM',
    period: 'Morning',
    status: 'taken',
    takenTime: '08:05 AM',
    refillDaysLeft: 18,
    totalPills: 30,
    remainingPills: 18,
    color: '#0ea5e9',
    audioReminder: 'Gentle morning chime',
  },
  {
    id: 'med-2',
    name: 'Metformin HCl',
    dosage: '500mg',
    instructions: '1 Tablet • With Lunch • Full glass of water',
    scheduledTime: '01:00 PM',
    period: 'Afternoon',
    status: 'upcoming',
    refillDaysLeft: 12,
    totalPills: 60,
    remainingPills: 24,
    color: '#06b6d4',
    audioReminder: 'Voice announcement: Time for Metformin',
  },
  {
    id: 'med-3',
    name: 'Lisinopril',
    dosage: '10mg',
    instructions: '1 Tablet • Afternoon blood pressure regulator',
    scheduledTime: '01:30 PM',
    period: 'Afternoon',
    status: 'upcoming',
    refillDaysLeft: 22,
    totalPills: 30,
    remainingPills: 22,
    color: '#3b82f6',
    audioReminder: 'Gentle pulse chime',
  },
  {
    id: 'med-4',
    name: 'Amlodipine Besylate',
    dosage: '5mg',
    instructions: '1 Tablet • Before bedtime with water',
    scheduledTime: '08:00 PM',
    period: 'Night',
    status: 'upcoming',
    refillDaysLeft: 25,
    totalPills: 30,
    remainingPills: 25,
    color: '#8b5cf6',
    audioReminder: 'Soft evening harp',
  },
];

export const initialVitals: VitalMetric[] = [
  {
    id: 'vital-bp',
    title: 'BLOOD PRESSURE',
    category: 'bp',
    value: '120/78',
    unit: 'mmHg',
    statusLabel: 'Optimal • Normal Range',
    statusType: 'optimal',
    note: 'Last taken: Today, 8:15 AM',
    sparkline: [122, 124, 121, 125, 119, 122, 120],
    timestamp: 'Today, 8:15 AM',
  },
  {
    id: 'vital-sugar',
    title: 'BLOOD SUGAR',
    category: 'sugar',
    value: '96',
    unit: 'mg/dL',
    statusLabel: 'Fasting Normal',
    statusType: 'optimal',
    note: 'Before Breakfast',
    sparkline: [98, 102, 95, 99, 94, 98, 96],
    timestamp: 'Today, 7:55 AM',
  },
  {
    id: 'vital-heart',
    title: 'HEART RATE',
    category: 'heart',
    value: '72',
    unit: 'BPM',
    statusLabel: 'Healthy Rhythm',
    statusType: 'optimal',
    note: 'Smartwatch Auto-sync',
    sparkline: [70, 74, 71, 75, 73, 70, 72],
    timestamp: 'Synced 2m ago',
  },
  {
    id: 'vital-temp',
    title: 'TEMPERATURE',
    category: 'temp',
    value: '98.4',
    unit: '°F',
    statusLabel: 'Stable • Normal',
    statusType: 'optimal',
    note: 'Logged Yesterday evening',
    sparkline: [98.6, 98.4, 98.5, 98.3, 98.6, 98.4, 98.4],
    timestamp: 'Yesterday, 6:30 PM',
  },
];

export const weeklyHistoryVitals: DayVitals[] = [
  { day: 'Mon', systolic: 122, diastolic: 80, glucose: 98, heartRate: 71 },
  { day: 'Tue', systolic: 124, diastolic: 82, glucose: 102, heartRate: 74 },
  { day: 'Wed', systolic: 119, diastolic: 78, glucose: 95, heartRate: 70 },
  { day: 'Thu', systolic: 121, diastolic: 79, glucose: 99, heartRate: 72 },
  { day: 'Fri', systolic: 118, diastolic: 76, glucose: 94, heartRate: 69 },
  { day: 'Sat', systolic: 121, diastolic: 80, glucose: 97, heartRate: 73 },
  { day: 'Sun', systolic: 120, diastolic: 78, glucose: 96, heartRate: 72 },
];

export const initialDocuments: ClinicalDocument[] = [
  {
    id: 'doc-1',
    title: 'Cardiology Consultation Summary',
    type: 'PDF',
    doctorOrLab: 'Dr. Aris Thorne • Oct 14, 2024',
    date: 'Oct 14, 2024',
    size: '1.4 MB',
    summary: 'Routine 6-month cardiac checkup. Left ventricular function normal (EF 60%). Blood pressure well-controlled on current regimen. Maintain Lisinopril 10mg and Atorvastatin 20mg.',
    tags: ['Cardiology', 'Consultation', 'Dr. Thorne', 'Annual Exam'],
  },
  {
    id: 'doc-2',
    title: 'Complete Blood Count (CBC) Panel',
    type: 'LAB',
    doctorOrLab: 'Metropolitan Diagnostic • Oct 2024',
    date: 'Oct 08, 2024',
    size: '840 KB',
    summary: 'Hemoglobin: 14.2 g/dL (Normal). Platelets: 240,000 /mcL (Normal). White Blood Cells: 6.8 K/uL. Fasting A1c at 6.4%, stable glycemic control maintained.',
    tags: ['Blood Panel', 'Metropolitan Diagnostic', 'A1c Test', 'CBC'],
  },
  {
    id: 'doc-3',
    title: 'Annual Prescription Slip',
    type: 'RX',
    doctorOrLab: 'Renewed till Dec 2025 • 3 Active Drugs',
    date: 'Sep 28, 2024',
    size: '620 KB',
    summary: 'Official electronic prescription order issued by Dr. Aris Thorne. Includes Atorvastatin 20mg (90-day refill), Metformin HCl 500mg, Lisinopril 10mg.',
    tags: ['Prescription', 'Pharmacy Order', 'Refills Authorized'],
  },
  {
    id: 'doc-4',
    title: 'Diabetic Retinopathy Ophthalmology Screen',
    type: 'PDF',
    doctorOrLab: 'Dr. Elena Rostova • Vision Care • Sept 2024',
    date: 'Sep 15, 2024',
    size: '2.1 MB',
    summary: 'Dilated eye examination confirmed no evidence of diabetic retinopathy, maculopathy, or glaucoma. Lens clear. Next follow-up recommended in 12 months.',
    tags: ['Ophthalmology', 'Retina Scan', 'Diabetes Screen'],
  },
];

export const initialCaregiverAlerts: CaregiverAlert[] = [
  {
    id: 'alert-1',
    title: 'Arthur took morning medication',
    description: 'Atorvastatin 20mg • Confirmed taken at 8:05 AM with breakfast',
    type: 'dose_taken',
    timestamp: 'Today, 8:05 AM',
    status: 'confirmed',
  },
  {
    id: 'alert-2',
    title: 'New Vitals Logged: 120/78 mmHg',
    description: 'Blood pressure in physician-approved optimal safe corridor',
    type: 'vital_logged',
    timestamp: 'Today, 8:15 AM',
    status: 'normal',
  },
  {
    id: 'alert-3',
    title: 'Automated Call & SMS Fallback Active',
    description: 'Notifies primary caregiver Sarah only if an afternoon dose is delayed by 45 mins',
    type: 'fallback_alert',
    timestamp: 'Monitored 24/7',
    status: 'active',
  },
];
